const topics = {
  PRODUCT_CREATED: "PRODUCT_CREATED",
  PRODUCT_UPDATED: "PRODUCT_UPDATED",
  PRODUCT_DELETED: "PRODUCT_DELETED",

  USER_CREATED: "USER_CREATED",
  USER_DELETED: "USER_DELETED",
};

module.exports = topics;

